name: 一饭的博客
author: jql
baseurl: 
description: 一饭的博客
github: https://github.com/HadesJK
#twitter123: http://www.twitter.com/
#facebook123: http://www.facebook.com
#linkedin123: http://www.linkedin.com
#email123: rnpatel[at]me.com
#location123: 42°2'16"N   70°12'47"W
#disqus123: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
